version: '3'
services:
    web1:
        build: Service_1/.
        ports:
            - "8001:81"
        volumes:
            - .:/code
        networks:
          - app-net
    web2:
        build: Service_2/.
        ports:
            - "8002:82"
        volumes:
            - .:/code
        networks:
          - app-net
    web3:
        build: Service_3/.
        ports:
            - "8003:83"
        volumes:
            - .:/code
        networks:
          - app-net
    frontend:
        build: frontend/.
        environment:
          - NODE_ENV=development
        volumes:
          - ./:/usr/src/app
        command: sh -c 'cd frontend/app && yarn start'
        networks:
          - app-net
        ports:
          - '3000:3000'
        tty: true
    mongodb:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: mongo
      ports:
        - 27017:27017
      volumes:
        - ./db:/data/db
        - ./configdb:/data/configdb
networks:
  app-net:
    driver: bridge